PROBLEM STATEMENT - PREDICT THE MAX TEMP BASED ON THE MIN TEMP (Dataset- Weather.csv)

In [4]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [6]:
df=pd.read_csv(r'C:\Users\Asus\Downloads\weather_csv\Weather.csv')

In [7]:
df.head()

STA      Date Precip  WindGustSpd    MaxTemp    MinTemp   MeanTemp  \
0  10001  7/1/1942  1.016          NaN  25.555556  22.222222  23.888889   
1  10001  7/2/1942      0          NaN  28.888889  21.666667  25.555556   
2  10001  7/3/1942   2.54          NaN  26.111111  22.222222  24.444444   
3  10001  7/4/1942   2.54          NaN  26.666667  22.222222  24.444444   
4  10001  7/5/1942      0          NaN  26.666667  21.666667  24.444444   

  Snowfall PoorWeather  YR  ...  FT  FB FTI  PGT  TSHDSBRSGF  SD3  RHX  RHN  \
0      0.0         NaN  42  ... NaN NaN NaN  NaN         NaN  NaN  NaN  NaN   
1      0.0         NaN  42  ... NaN NaN NaN  NaN         NaN  NaN  NaN  NaN   
2      0.0         NaN  42  ... NaN NaN NaN  NaN         NaN  NaN  NaN  NaN   
3      0.0         NaN  42  ... NaN NaN NaN  NaN         NaN  NaN  NaN  NaN   
4      0.0         NaN  42  ... NaN NaN NaN  NaN         NaN  NaN  NaN  NaN   

  RVG  WTE  
0 NaN  NaN  
1 NaN  NaN  
2 NaN  NaN  
3 NaN  NaN  
4 NaN  NaN  

[5 rows x 30 columns]

In [8]:
df.tail()

STA        Date Precip  WindGustSpd    MaxTemp    MinTemp  \
119035  82506  12/27/1945      0          NaN  28.333333  18.333333   
119036  82506  12/28/1945  9.906          NaN  29.444444  18.333333   
119037  82506  12/29/1945      0          NaN  28.333333  18.333333   
119038  82506  12/30/1945      0          NaN  28.333333  18.333333   
119039  82506  12/31/1945      0          NaN  29.444444  17.222222   

         MeanTemp Snowfall PoorWeather  YR  ...  FT  FB FTI  PGT  TSHDSBRSGF  \
119035  23.333333      0.0         NaN  45  ... NaN NaN NaN  NaN         NaN   
119036  23.888889      0.0         1.0  45  ... NaN NaN NaN  NaN         1.0   
119037  23.333333      0.0         1.0  45  ... NaN NaN NaN  NaN         1.0   
119038  23.333333      0.0         NaN  45  ... NaN NaN NaN  NaN         NaN   
119039  23.333333      0.0         NaN  45  ... NaN NaN NaN  NaN         NaN   

        SD3  RHX  RHN RVG  WTE  
119035  NaN  NaN  NaN NaN  NaN  
119036  NaN  NaN  NaN NaN  NaN  
119037  NaN  NaN  NaN NaN  NaN  
119038  NaN  NaN  NaN NaN  NaN  
119039  NaN  NaN  NaN NaN  NaN  

[5 rows x 30 columns]

In [10]:
df.dtypes

STA              int64
Date            object
Precip          object
WindGustSpd    float64
MaxTemp        float64
MinTemp        float64
MeanTemp       float64
Snowfall        object
PoorWeather     object
YR               int64
MO               int64
DA               int64
PRCP            object
DR             float64
SPD            float64
MAX            float64
MIN            float64
MEA            float64
SNF             object
SND            float64
FT             float64
FB             float64
FTI            float64
PGT            float64
TSHDSBRSGF      object
SD3            float64
RHX            float64
RHN            float64
RVG            float64
WTE            float64
dtype: object

In [13]:
df.isna()

STA   Date  Precip  WindGustSpd  MaxTemp  MinTemp  MeanTemp  \
0       False  False   False         True    False    False     False   
1       False  False   False         True    False    False     False   
2       False  False   False         True    False    False     False   
3       False  False   False         True    False    False     False   
4       False  False   False         True    False    False     False   
...       ...    ...     ...          ...      ...      ...       ...   
119035  False  False   False         True    False    False     False   
119036  False  False   False         True    False    False     False   
119037  False  False   False         True    False    False     False   
119038  False  False   False         True    False    False     False   
119039  False  False   False         True    False    False     False   

        Snowfall  PoorWeather     YR  ...    FT    FB   FTI   PGT  TSHDSBRSGF  \
0          False         True  False  ...  True  True  True  True        True   
1          False         True  False  ...  True  True  True  True        True   
2          False         True  False  ...  True  True  True  True        True   
3          False         True  False  ...  True  True  True  True        True   
4          False         True  False  ...  True  True  True  True        True   
...          ...          ...    ...  ...   ...   ...   ...   ...         ...   
119035     False         True  False  ...  True  True  True  True        True   
119036     False        False  False  ...  True  True  True  True       False   
119037     False        False  False  ...  True  True  True  True       False   
119038     False         True  False  ...  True  True  True  True        True   
119039     False         True  False  ...  True  True  True  True        True   

         SD3   RHX   RHN   RVG   WTE  
0       True  True  True  True  True  
1       True  True  True  True  True  
2       True  True  True  True  True  
3       True  True  True  True  True  
4       True  True  True  True  True  
...      ...   ...   ...   ...   ...  
119035  True  True  True  True  True  
119036  True  True  True  True  True  
119037  True  True  True  True  True  
119038  True  True  True  True  True  
119039  True  True  True  True  True  

[119040 rows x 30 columns]

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119040 entries, 0 to 119039
Data columns (total 30 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   STA          119040 non-null  int64  
 1   Date         119040 non-null  object 
 2   Precip       119040 non-null  object 
 3   WindGustSpd  532 non-null     float64
 4   MaxTemp      119040 non-null  float64
 5   MinTemp      119040 non-null  float64
 6   MeanTemp     119040 non-null  float64
 7   Snowfall     117877 non-null  object 
 8   PoorWeather  34237 non-null   object 
 9   YR           119040 non-null  int64  
 10  MO           119040 non-null  int64  
 11  DA           119040 non-null  int64  
 12  PRCP         117108 non-null  object 
 13  DR           533 non-null     float64
 14  SPD          532 non-null     float64
 15  MAX          118566 non-null  float64
 16  MIN          118572 non-null  float64
 17  MEA          118542 non-null  float64
 18  SNF          117877 non-

In [19]:
df.describe().T

count          mean           std           min           25%  \
STA          119040.0  29659.435795  20953.209402  10001.000000  11801.000000   
WindGustSpd     532.0     37.774534     10.297808     18.520000     29.632000   
MaxTemp      119040.0     27.045111      8.717817    -33.333333     25.555556   
MinTemp      119040.0     17.789511      8.334572    -38.333333     15.000000   
MeanTemp     119040.0     22.411631      8.297982    -35.555556     20.555556   
YR           119040.0     43.805284      1.136718     40.000000     43.000000   
MO           119040.0      6.726016      3.425561      1.000000      4.000000   
DA           119040.0     15.797530      8.794541      1.000000      8.000000   
DR              533.0     26.998124     15.221732      2.000000     11.000000   
SPD             532.0     20.396617      5.560371     10.000000     16.000000   
MAX          118566.0     81.003745     14.869361    -28.000000     78.000000   
MIN          118572.0     64.273808     14.481498    -37.000000     59.000000   
MEA          118542.0     72.644843     14.211082    -32.000000     69.000000   
SND            5563.0      0.000000      0.000000      0.000000      0.000000   
FT                0.0           NaN           NaN           NaN           NaN   
FB                0.0           NaN           NaN           NaN           NaN   
FTI               0.0           NaN           NaN           NaN           NaN   
PGT             525.0     12.085333      5.731328      0.000000      8.500000   
SD3               0.0           NaN           NaN           NaN           NaN   
RHX               0.0           NaN           NaN           NaN           NaN   
RHN               0.0           NaN           NaN           NaN           NaN   
RVG               0.0           NaN           NaN           NaN           NaN   
WTE               0.0           NaN           NaN           NaN           NaN   

                      50%           75%           max  
STA          22508.000000  33501.000000  82506.000000  
WindGustSpd     37.040000     43.059000     75.932000  
MaxTemp         29.444444     31.666667     50.000000  
MinTemp         21.111111     23.333333     34.444444  
MeanTemp        25.555556     27.222222     40.000000  
YR              44.000000     45.000000     45.000000  
MO               7.000000     10.000000     12.000000  
DA              16.000000     23.000000     31.000000  
DR              32.000000     34.000000     78.000000  
SPD             20.000000     23.250000     41.000000  
MAX             85.000000     89.000000    122.000000  
MIN             70.000000     74.000000     94.000000  
MEA             78.000000     81.000000    104.000000  
SND              0.000000      0.000000      0.000000  
FT                    NaN           NaN           NaN  
FB                    NaN           NaN           NaN  
FTI                   NaN           NaN           NaN  
PGT             11.600000     15.000000     23.900000  
SD3                   NaN           NaN           NaN  
RHX                   NaN           NaN           NaN  
RHN                   NaN           NaN           NaN  
RVG                   NaN           NaN           NaN  
WTE                   NaN           NaN           NaN

In [24]:
df.isna().apply(pd.value_counts).T

False      True
STA          119040.0       NaN
Date         119040.0       NaN
Precip       119040.0       NaN
WindGustSpd     532.0  118508.0
MaxTemp      119040.0       NaN
MinTemp      119040.0       NaN
MeanTemp     119040.0       NaN
Snowfall     117877.0    1163.0
PoorWeather   34237.0   84803.0
YR           119040.0       NaN
MO           119040.0       NaN
DA           119040.0       NaN
PRCP         117108.0    1932.0
DR              533.0  118507.0
SPD             532.0  118508.0
MAX          118566.0     474.0
MIN          118572.0     468.0
MEA          118542.0     498.0
SNF          117877.0    1163.0
SND            5563.0  113477.0
FT                NaN  119040.0
FB                NaN  119040.0
FTI               NaN  119040.0
PGT             525.0  118515.0
TSHDSBRSGF    34237.0   84803.0
SD3               NaN  119040.0
RHX               NaN  119040.0
RHN               NaN  119040.0
RVG               NaN  119040.0
WTE               NaN  119040.0

In [ ]:
#Predict maximum temperature when the minimum temperatures are given

In [ ]:
#Let us take X as the independent Feature/Variable. here X-> Minimum Temperature(given)

In [30]:
X=df[['MinTemp']] 

In [28]:
X.shape

(119040, 1)

In [33]:
X.head()

MinTemp
0  22.222222
1  21.666667
2  22.222222
3  22.222222
4  21.666667

In [ ]:
#Let us take y as the dependent/target variable. here y-> Maximum temperature(to be predicted)

In [31]:
y=df[['MaxTemp']]

In [32]:
y.shape

(119040, 1)

In [34]:
y.head()

MaxTemp
0  25.555556
1  28.888889
2  26.111111
3  26.666667
4  26.666667

In [ ]:
#lets make sure that are dependent and independent feature/variable does not contain null values

In [37]:
X.isna().apply(pd.value_counts).T

False
MinTemp  119040

In [38]:
y.isna().apply(pd.value_counts).T

False
MaxTemp  119040

In [ ]:
#Lets first train_test_split our data

In [39]:
from sklearn.model_selection import train_test_split

In [ ]:
#Split the data set in 70:30 -> Train:Test (ideal)

In [41]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,test_size=0.3,random_state=1)

In [42]:
X_train.shape

(83328, 1)

In [43]:
X_test.shape

(35712, 1)

In [44]:
y_train.shape

(83328, 1)

In [45]:
y_test.shape

(35712, 1)

In [ ]:
#Importing the LinearRegression model 

In [46]:
from sklearn.linear_model import LinearRegression

In [ ]:
#first create object class of the LinearRegression Model

In [47]:
model=LinearRegression()

In [ ]:
#Lets now train our ML algorithm -.fit()

In [48]:
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
#Predict the data on test data -> these are our predicted values

y_pred=model.predict(X_test)

In [52]:
y_pred

array([[20.88972865],
       [28.56451499],
       [31.63442954],
       ...,
       [31.12277711],
       [28.56451499],
       [31.12277711]])

In [ ]:
#Accuracy of the test model which is equivalent to r2_score

In [54]:
model.score(X_test,y_test)*100

76.58019339654669

In [ ]:
#Accuracy pf the train model

In [56]:
model.score(X_train,y_train)*100

77.3970250594516

In [ ]:
#The accuracy of the test and train models must be nearly equal to each other. 
#Then this can be considered to be good trained/good fit model. Our model tes and train scores are equivalent to eaach other so it's a good fit model.

In [59]:
#lets calculate the slope and intercept of our LinearRegression model
model.coef_

array([[0.92097436]])

In [60]:
model.intercept_

array([10.65668019])

In [ ]:
#Lets calculate r2 Score

In [61]:
from sklearn.metrics import r2_score

In [62]:
r2=r2_score(y_test,y_pred)

In [63]:
r2*100

76.58019339654669

In [ ]:
#Adjusted R2 score -> calculated by dividing the residual mean square error by the total mean square error and the result is subtracted from 1
#Adjusted R2 score must be always less than r2 Score

In [66]:
n=len(df)
p=len(y_test)

In [67]:
Adjusted_r2=1-(1-r2)*(n-1)/(n-p-1)

In [68]:
Adjusted_r2*100

66.54301296976396